sources += files(
'raylib/rlgl.c',
'raylib/rlutils.c',
'raylib/rshapes.c',
'raylib/rtextures.c',
'glad/gl.c',
'BigTexture.cpp',
'BlendMode.cpp',
'Camera.cpp',
'Draw.cpp',
'GLCheck.cpp',
'GLState.cpp',
'GraphicalPrimitive.cpp',
'RenderBatch.cpp',
'RenderMan.cpp',
'RenderTarget.cpp',
'Shader.cpp',
'Shapes.cpp',
'Texture.cpp',
'Vertex.cpp',
)
